deskpro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from rest_framework_simplejwt.views import TokenRefreshView

from app.views import *

router = routers.DefaultRouter()
router.register(r'ticket',  TicketViewSet, base_name='ticket')
router.register(r'message', MessageViewSet, base_name='message')
router.register(r'agent', AgentViewSet, base_name='agent')
router.register(r'client', ClientViewSet, base_name='client')
router.register(r'team', TeamViewSet, base_name='team')
router.register(r'tag', TagViewSet, base_name='tag')
router.register(r'register', RegisterViewSet, base_name='auth')
router.register(r'triggers', CriteriaViewSet, base_name='triggers')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home),
    path('initial', initial),
    path('initial-images', create_images),
    path('api/filter/', filterr),
    # path('summernote/', include('django_summernote.urls')),
    # path('tickets/', tickets_page),
    # path('ticket-setting/<int:pk>/', submit_ticket_setting),
    # path('ticket/<int:pk>/', ticket_detail),
    # path('login/', login, name='login'),
    # path('register/', register, name='register'),
    # path('logout/', logout, name='logout'),
    # path('profile/', profile, name='profile'),
    # path('user/<int:pk>/', user_detail),
    path('api/token/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/', include(router.urls)),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from io import BytesIO, StringIO

from PIL.ImageColor import getrgb
from django.contrib.auth.models import AbstractUser
from django.core.files.base import ContentFile
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import SET_NULL, CASCADE, Q
from django.utils import timezone
from PIL import Image, ImageDraw, ImageFont
from django.utils.crypto import get_random_string
import operator


class User(AbstractUser):
    avatar = models.ImageField(upload_to="avatar/", null=True, blank=True)
    team = models.ForeignKey("Team", blank=True, null=True, on_delete=SET_NULL)
    signature = models.TextField(default="", blank=True, null=True)
    company = models.ForeignKey("Company", on_delete=CASCADE, null=True, blank=True)
    invitation = models.ForeignKey("Invitation", on_delete=CASCADE, null=True, blank=True)
    phone_number = models.CharField(max_length=11, null=True, blank=True)

    def get_avatar(self):
        if self.avatar:
            return "http://127.0.0.1:8000" + self.avatar.url
        return None

    def save(self, *args, **kwargs):
        if not self.avatar:
            self.avatar = "avatar/image_" + self.username[0].lower() + ".png"
        super(User, self).save(*args, **kwargs)


class ClientProfile(models.Model):
    name = models.CharField(max_length=255)
    avatar = models.ImageField(upload_to="avatar/", null=True, blank=True)
    company = models.ForeignKey("Company", on_delete=CASCADE, null=True, blank=True)

    def get_avatar(self):
        if self.avatar:
            return "http://127.0.0.1:8000" + self.avatar.url
        return None

    def save(self, *args, **kwargs):
        if not self.avatar:
            self.avatar = "avatar/image_" + self.name[0].lower() + ".png"
            colors = [
                "#1abc9c", "#2ecc71", "#3498db", "#9b59b6", "#34495e", "#16a085", "#27ae60", "#2980b9", "#8e44ad",
                "#f1c40f", "#e67e22", "#e74c3c", "#f39c12", "#d35400", "#c0392b",
            ]
            img = Image.new('RGB', (64, 64), getrgb(colors[ord(self.name[0].upper()) % 15]))
            img_io = BytesIO()
            font = ImageFont.truetype('../../arial.ttf', 35)
            draw = ImageDraw.Draw(img)
            w, h = draw.textsize(self.name[0].upper(), font=font)
            draw.text(((64 - w) / 2, (54 - h) / 2), self.name[0].upper(), font=font, fill=(255, 255, 255))
            img.save(img_io, format='PNG', quality=100)
            self.avatar = ContentFile(img_io.getvalue(), 'image_'+self.name[0].upper()+'.png')
        super(ClientProfile, self).save(*args, **kwargs)


class Client(models.Model):
    email = models.EmailField()
    profile = models.ForeignKey(ClientProfile, on_delete=CASCADE,null=True,blank=True)


class Tag(models.Model):
    name = models.CharField(max_length=255)
    creation_time = models.DateTimeField(default=timezone.now)
    company = models.ForeignKey("Company", on_delete=CASCADE)

    def __str__(self):
        return self.name


class Team(models.Model):
    name = models.CharField(max_length=255, null=False, blank=False)
    company = models.ForeignKey("Company", on_delete=CASCADE)

    def __str__(self):
        return self.name


class Message(models.Model):
    client_sender = models.ForeignKey(Client, on_delete=SET_NULL, null=True, blank=True)
    agent_sender = models.ForeignKey(User, on_delete=SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=255, default="no subject")
    content = models.TextField()
    creation_time = models.DateTimeField(default=timezone.now)
    is_note = models.BooleanField(default=False)
    ticket = models.ForeignKey("Ticket", on_delete=CASCADE, null=True, blank=True)

    def __str__(self):
        return self.title

    def is_agent_message(self):
        return self.agent_sender is not None

    def save(self, *args, **kwargs):
        if not self.is_agent_message():
            if Ticket.objects.filter(client_id=self.client_sender.id, status=Ticket.STATUS_AWAITING_USER).exists():
                ticket = Ticket.objects.get(client_id=self.client_sender.id, status=Ticket.STATUS_AWAITING_USER)
            else:
                ticket = Ticket.objects.create(client=self.client_sender, title=self.title,
                                               company=Company.objects.first())
            self.ticket = ticket
        super(Message, self).save(*args, **kwargs)


class Ticket(models.Model):
    STATUS_AWAITING_USER = 0
    STATUS_AWAITING_AGENT = 1
    STATUS_RESOLVED = 2
    STATUS_CHOICES = (
        (STATUS_AWAITING_USER, "Awaiting user"),
        (STATUS_AWAITING_AGENT, "Awaiting agent"),
        (STATUS_RESOLVED, "Resolved"),
    )
    STATUSES = {k: v for (k, v) in STATUS_CHOICES}

    client = models.ForeignKey(Client, on_delete=CASCADE, null=True, blank=True, related_name="starter")
    title = models.CharField(max_length=255, default="no subject")
    creation_time = models.DateTimeField(default=timezone.now)
    status = models.IntegerField(choices=STATUS_CHOICES, default=STATUS_AWAITING_AGENT)
    priority = models.SmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)], default=1)
    tags = models.ManyToManyField(Tag, blank=True)
    assigned_to = models.ForeignKey(User, on_delete=SET_NULL, null=True, related_name="assigned_to")
    assigned_team = models.ForeignKey(Team, on_delete=SET_NULL, null=True)
    followers = models.ManyToManyField(User, related_name="follows")
    company = models.ForeignKey("Company", on_delete=CASCADE)

    def __str__(self):
        return self.title

    def get_status_name(self):
        return self.STATUSES.get(self.status)


class Filter(models.Model):
    name = models.CharField(max_length=255)
    query = models.CharField(max_length=1023)
    agent = models.ForeignKey(User, on_delete=CASCADE)

    def __str__(self):
        return self.name


class Company(models.Model):
    name = models.CharField(max_length=255)
    creation_time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


class Invitation(models.Model):
    creation_time = models.DateTimeField(default=timezone.now)
    inviter = models.ForeignKey(User, on_delete=SET_NULL, null=True, related_name="inviter")
    key = models.CharField(max_length=64)

    def save(self, *args, **kwargs):
        self.key = get_random_string(64).lower()
        super(Invitation, self).save(*args, **kwargs)


class Criteria(models.Model):
    name = models.CharField(max_length=255)

    def is_valid_for(self, ticket):
        for criteria_clause in self.clauses.all():
            if criteria_clause.is_valid_for(ticket):
                return True

        return False

    def get_query(self, user):
        # query = Q()
        # for clause in self.clauses.all():
        #     query = Q | clause.get_query()

        return self.clauses.first().get_query(user)


class CriteriaClause(models.Model):
    criteria = models.ForeignKey(Criteria, on_delete=CASCADE, related_name="clauses")

    def is_valid_for(self, ticket):
        for single_criteria in self.singles.all():
            if not single_criteria.is_valid_for(ticket):
                return False

        return True

    def get_query(self, user):
        query = Q()
        for single_criteria in self.singles.all():
            query = query & single_criteria.get_query(user)

        return query


class SingleCriteria(models.Model):
    field = models.CharField(max_length=255)
    value = models.CharField(max_length=255)
    value_type = models.CharField(max_length=255, default="string")
    operation = models.CharField(max_length=255)
    criteria_clause = models.ForeignKey(CriteriaClause, on_delete=CASCADE, related_name="singles", null=True,
                                        blank=True)

    def is_valid_for(self, ticket):
        if not operator.attrgetter(self.field)(ticket):
            return False

        ticket_value = operator.attrgetter(self.field)(ticket)
        value = self.value
        if self.value_type == "int":
            value = int(self.value)

        if self.operation == "is":
            return ticket_value == value
        if self.operation == "is not":
            return ticket_value != value
        if self.operation == "greater than":
            return ticket_value > value
        if self.operation == "less than":
            return ticket_value < value
        if self.operation == "contains":
            return value in ticket_value
        if self.operation == "not contains":
            return value not in ticket_value
        if self.operation == "isnull":
            return value is None

        return False

    def get_standard_operation(self):
        if self.operation == "is":
            return ""
        if self.operation == "is not":
            return ""
        if self.operation == "greater than":
            return "__gt"
        if self.operation == "less than":
            return "__lt"
        if self.operation == "contains":
            return "__contains"
        if self.operation == "not contains":
            return "__contains"
        if self.operation == "isnull":
            return "__isnull"

    def get_query(self, user):
        value = self.value
        if self.value == "shooka_current_agent":
            value = user.id
        elif self.value == "shooka_current_agent_team":
            if user.team is None:
                return Q(pk__isnull=True)
            value = user.team_id
        elif self.value_type == "int":
            value = int(self.value)
        elif self.value_type == "boolean":
            value = bool(self.value)
        key = self.field.replace(".", "__") + self.get_standard_operation()
        if self.operation.startswith("not"):
            return ~Q(**{key: value})
        else:
            return Q(**{key: value})

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Desk Pro</title>
</head>
<body>
<a href="../login/">login</a>
<br>
<a href="../logout/">logout</a>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <style>
        html,
        body {
            height: 100%;
        }

        body {
            display: -ms-flexbox;
            display: flex;
            -ms-flex-align: center;
            align-items: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: auto;
            margin-top: 20px;
        }

        .form-signin .checkbox {
            font-weight: 400;
        }

        .form-signin .form-control {
            position: relative;
            box-sizing: border-box;
            height: auto;
            padding: 10px;
            font-size: 16px;
        }

        .form-signin .form-control:focus {
            z-index: 2;
        }

        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
    </style>
</head>
<body class="text-center">
<form method="post" class="form-signin">
    {% csrf_token %}
    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
    <label for="inputUsername" class="sr-only">Username</label>
    <input type="text" id="inputUsername" class="form-control" placeholder="Username" name="username" required
           autofocus>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" id="inputPassword" class="form-control" placeholder="Password" name="password" required>
    <div class="checkbox mb-3">
        <label>
            <input type="checkbox" value="remember-me"> Remember me
        </label>
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
</form>
</body>
</html>

templates/panel.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


    <title>
        {% block title %}
            Deskpro
        {% endblock %}
    </title>

    {% block styles %}{% endblock %}
    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


    <!-- Custom styles for this template -->
    <style>
        body {
            font-size: .875rem;
            background-color: #dddddd;
        }

        .feather {
            width: 16px;
            height: 16px;
            vertical-align: text-bottom;
        }

        /*
         * Sidebar
         */

        .sidebar {
            position: fixed;
            top: 0;
            bottom: 0;
            left: 0;
            z-index: 100; /* Behind the navbar */
            padding: 48px 0 0; /* Height of navbar */
            box-shadow: inset -1px 0 0 rgba(0, 0, 0, .1);
        }

        .sidebar-sticky {
            position: relative;
            top: 0;
            height: calc(100vh - 48px);
            padding-top: .5rem;
            overflow-x: hidden;
            overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
        }

        @supports ((position: -webkit-sticky) or (position: sticky)) {
            .sidebar-sticky {
                position: -webkit-sticky;
                position: sticky;
            }
        }

        .sidebar .nav-link {
            font-weight: 500;
            color: #333;
        }

        .sidebar .nav-link .feather {
            margin-right: 4px;
            color: #999;
        }

        .sidebar .nav-link.active {
            color: #007bff;
        }

        .sidebar .nav-link:hover .feather,
        .sidebar .nav-link.active .feather {
            color: inherit;
        }

        .sidebar-heading {
            font-size: .75rem;
            text-transform: uppercase;
        }

        /*
         * Content
         */

        [role="main"] {
            padding-top: 48px; /* Space for fixed navbar */
        }

        /*
         * Navbar
         */

        .navbar-brand {
            padding-top: .75rem;
            padding-bottom: .75rem;
            font-size: 1rem;
            background-color: rgba(0, 0, 0, .25);
            box-shadow: inset -1px 0 0 rgba(0, 0, 0, .25);
        }

        .navbar .form-control {
            padding: .75rem 1rem;
            border-width: 0;
            border-radius: 0;
        }

        .form-control-dark {
            color: #fff;
            background-color: rgba(255, 255, 255, .1);
            border-color: rgba(255, 255, 255, .1);
        }

        .form-control-dark:focus {
            border-color: transparent;
            box-shadow: 0 0 0 3px rgba(255, 255, 255, .25);
        }
    </style>
</head>

<body>
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Company name</a>
    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            <a class="nav-link" href="/logout/">logout</a>
        </li>
    </ul>
    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            <a class="nav-link" href="/profile/">profile</a>
        </li>
    </ul>
</nav>

<div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
            <div class="sidebar-sticky">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link active" href="/tickets/">
                            <span data-feather="home"></span>
                            All Tickets <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/tickets/?assigned_to__isnull=true">
                            <span data-feather="file"></span>
                            Unassigned Tickets
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/tickets/?assigned_to_id={{ current_agent.id }}">
                            <span data-feather="shopping-cart"></span>
                            My Tickets
                        </a>
                    </li>
                    {% if current_agent.team %}
                    <li class="nav-item">
                        <a class="nav-link" href="/tickets/?assigned_team_id={{ current_agent.team.id }}">
                            <span data-feather="users"></span>
                            My Team's Tickets
                        </a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="/tickets/?followers__id={{ request.user.id}}">
                            <span data-feather="bar-chart-2"></span>
                            Tickets I Follow
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="layers"></span>
                            Integrations
                        </a>
                    </li>
                </ul>

                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                    <span>Saved reports</span>
                    <a class="d-flex align-items-center text-muted" href="#">
                        <span data-feather="plus-circle"></span>
                    </a>
                </h6>
                <ul class="nav flex-column mb-2">
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Current month
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Last quarter
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Social engagement
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Year-end sale
                        </a>
                    </li>
                </ul>
                {% if current_agent.filter_set %}
                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>filters</span>
                        <a class="d-flex align-items-center text-muted" href="#">
                            <span data-feather="plus-circle"></span>
                        </a>
                    </h6>
                    <ul class="nav flex-column mb-2">
                        {% for filter in current_agent.filter_set.all %}
                            <li class="nav-item">
                                <a class="nav-link" href="/tickets/?{{ filter.query }}">
                                    <span data-feather="file-text"></span>
                                    {{ filter.name }}
                                </a>
                            </li>
                        {% endfor %}

                    </ul>
                {% endif %}
            </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
            {% block content %}

            {% endblock %}
        </main>
    </div>
</div>


<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


<script>
    /*
     * LetterAvatar
     *
     * Artur Heinze
     * Create Letter avatar based on Initials
     * based on https://gist.github.com/leecrossley/6027780
     */
    (function (w, d) {


        function LetterAvatar(name, size) {

            name = name || '';
            size = size || 60;

            let colours = [
                    "#1abc9c", "#2ecc71", "#3498db", "#9b59b6", "#34495e", "#16a085", "#27ae60", "#2980b9", "#8e44ad", "#2c3e50",
                    "#f1c40f", "#e67e22", "#e74c3c", "#ecf0f1", "#95a5a6", "#f39c12", "#d35400", "#c0392b", "#bdc3c7", "#7f8c8d"
                ],

                nameSplit = String(name).toUpperCase().split(' '),
                initials, charIndex, colourIndex, canvas, context, dataURI;


            if (nameSplit.length === 1) {
                initials = nameSplit[0] ? nameSplit[0].charAt(0) : '?';
            } else {
                initials = nameSplit[0].charAt(0) + nameSplit[1].charAt(0);
            }

            if (w.devicePixelRatio) {
                size = (size * w.devicePixelRatio);
            }

            charIndex = (initials === '?' ? 72 : initials.charCodeAt(0)) - 64;
            colourIndex = charIndex % 20;
            canvas = d.createElement('canvas');
            canvas.width = size;
            canvas.height = size;
            context = canvas.getContext("2d");

            context.fillStyle = colours[colourIndex - 1];
            context.fillRect(0, 0, canvas.width, canvas.height);
            context.font = Math.round(canvas.width / 2) + "px Arial";
            context.textAlign = "center";
            context.fillStyle = "#FFF";
            context.fillText(initials, size / 2, size / 1.5);

            dataURI = canvas.toDataURL();
            canvas = null;

            return dataURI;
        }

        LetterAvatar.transform = function () {

            Array.prototype.forEach.call(d.querySelectorAll('img[avatar]'), function (img, name) {
                name = img.getAttribute('avatar');
                img.src = LetterAvatar(name, img.getAttribute('width'));
                img.removeAttribute('avatar');
                img.setAttribute('alt', name);
            });
        };


        // AMD support
        if (typeof define === 'function' && define.amd) {

            define(function () {
                return LetterAvatar;
            });

            // CommonJS and Node.js module support.
        } else if (typeof exports !== 'undefined') {

            // Support Node.js specific `module.exports` (which can be a function)
            if (typeof module !== 'undefined' && module.exports) {
                exports = module.exports = LetterAvatar;
            }

            // But always support CommonJS module 1.1.1 spec (`exports` cannot be a function)
            exports.LetterAvatar = LetterAvatar;

        } else {

            window.LetterAvatar = LetterAvatar;

            d.addEventListener('DOMContentLoaded', function (event) {
                LetterAvatar.transform();
            });
        }

    })(window, document);
</script>
{% block scripts %}
{% endblock %}
</body>
</html>

templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <style>
        html,
        body {
            height: 100%;
        }

        body {
            display: -ms-flexbox;
            display: flex;
            -ms-flex-align: center;
            align-items: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            width: 100%;
            max-width: 980px;
            padding: 15px;
            margin: auto;
            margin-top: 20px;
        }

        .form-signin .checkbox {
            font-weight: 400;
        }

        .form-signin .form-control {
            position: relative;
            box-sizing: border-box;
            height: auto;
            padding: 10px;
            font-size: 16px;
        }

        .form-signin .form-control:focus {
            z-index: 2;
        }

        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
    </style>
</head>
<body class="text-center">
<form method="post" class="form-signin">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-lg btn-primary btn-block" type="submit">Save Changes</button>
</form>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <style>
        html,
        body {
            height: 100%;
        }

        body {
            display: -ms-flexbox;
            display: flex;
            -ms-flex-align: center;
            align-items: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: auto;
            margin-top: 20px;
        }

        .form-signin .checkbox {
            font-weight: 400;
        }

        .form-signin .form-control {
            position: relative;
            box-sizing: border-box;
            height: auto;
            padding: 10px;
            font-size: 16px;
        }

        .form-signin .form-control:focus {
            z-index: 2;
        }

        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
    </style>
</head>
<body class="text-center">
<form method="post" class="form-signin">
    {% csrf_token %}
    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
    <label for="inputUsername" class="sr-only">Username</label>
    <input type="text" id="inputUsername" class="form-control" placeholder="Username" name="username" required
           autofocus>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" id="inputPassword" class="form-control" placeholder="Password" name="password" required>
    <label for="inputPassword2" class="sr-only">Password verification</label>
    <input type="password" id="inputPassword2" class="form-control" placeholder="Password" name="password2" required>
    <div class="checkbox mb-3">
        <label>
            <input type="checkbox" value="remember-me"> Remember me
        </label>
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>
</form>
</body>
</html>